// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9UlwjrjeVgeAsnlOiHVCPXDLYaUVx_vM',
    appId: '1:276657389300:web:15946ba21d919654a8a8a1',
    messagingSenderId: '276657389300',
    projectId: 'disneyhotstar-79d61',
    authDomain: 'disneyhotstar-79d61.firebaseapp.com',
    storageBucket: 'disneyhotstar-79d61.appspot.com',
    measurementId: 'G-QNYT8Z2TJT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9hQLaop5cTFLltQhhEqtZDSbqh2ju9Vk',
    appId: '1:276657389300:android:d7bfe2f5ac568d60a8a8a1',
    messagingSenderId: '276657389300',
    projectId: 'disneyhotstar-79d61',
    storageBucket: 'disneyhotstar-79d61.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmDjkrgYskKK9KI7BMoj8tI4GmsuTVGqQ',
    appId: '1:276657389300:ios:165f0e1867807414a8a8a1',
    messagingSenderId: '276657389300',
    projectId: 'disneyhotstar-79d61',
    storageBucket: 'disneyhotstar-79d61.appspot.com',
    iosBundleId: 'com.example.dindaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmDjkrgYskKK9KI7BMoj8tI4GmsuTVGqQ',
    appId: '1:276657389300:ios:165f0e1867807414a8a8a1',
    messagingSenderId: '276657389300',
    projectId: 'disneyhotstar-79d61',
    storageBucket: 'disneyhotstar-79d61.appspot.com',
    iosBundleId: 'com.example.dindaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9UlwjrjeVgeAsnlOiHVCPXDLYaUVx_vM',
    appId: '1:276657389300:web:aa148ea76162aa2da8a8a1',
    messagingSenderId: '276657389300',
    projectId: 'disneyhotstar-79d61',
    authDomain: 'disneyhotstar-79d61.firebaseapp.com',
    storageBucket: 'disneyhotstar-79d61.appspot.com',
    measurementId: 'G-6ZYN0WNLZ4',
  );
}
